#!/usr/bin/env python3
"""
Puddleford — Static episode page generator
=============================================
Generates one real, static HTML file per episode at build time, with the
correct <title>/og:*/twitter:*/JSON-LD baked directly into the <head>.

WHY THIS EXISTS
----------------
episode.html is a single static file shared by every episode; its real
per-episode title/description/artwork are only patched in by client-side
JS *after* the page loads (see the `loadPage()` IIFE in episode.html).
Social crawlers (Facebook, X/Twitter, Slack, Discord, WhatsApp, Telegram,
iMessage, etc.) do not execute JavaScript, so every shared episode link
rendered the same generic fallback card ("Episode — Puddleford", stock
cover image) instead of the real episode's title/artwork. This script
fixes that by pre-rendering a real HTML file per episode with the correct
metadata already in the markup, so crawlers (and search engines) see
the right thing without running any JS.

OUTPUT
------
  episodes/<slug>/index.html   — one per episode, slug = episode_slug(ep)
                                   (same md5-of-guid slug used elsewhere
                                   in the pipeline, e.g. episode-stats/).

The generated page is a *superset* of the old client-rendered episode.html:
it has correct meta baked in immediately, then loads the exact same client
script (unchanged from episode.html) to progressively enhance with stats,
wiki cross-references and transcript — so behaviour for a real visitor is
identical, only crawlers/link-preview bots see a difference (for the
better).

`episode.html?id=<guid>` is kept working as a redirect shim (see
episode.html's own small addition) so old shared links / bookmarks still
resolve, just without a rich preview (crawlers on *those* URLs still only
get the generic fallback, but new links generated by the site always use
the static path).

Usage:
  python3 scripts/generate_episode_pages.py
"""

import email.utils
import hashlib
import html
import json
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

RSS_URL = "https://anchor.fm/s/10ce1465c/podcast/rss"
WIKI_JSON = Path("data/wiki.json")
EPISODE_STATS_INDEX = Path("data/episode-stats/index.json")
TRANSCRIPT_INDEX = Path("data/transcripts/index.json")
OUT_DIR = Path("episodes")
SITE_URL = "https://puddleford.com"
DEFAULT_IMAGE = f"{SITE_URL}/assets/img/cover-with-title-1.jpg"

ITUNES_NS = "http://www.itunes.com/dtds/podcast-1.0.dtd"


def fetch_rss():
    req = urllib.request.Request(RSS_URL, headers={"User-Agent": "PuddlefordBot/1.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def parse_episodes(rss_bytes):
    ns = {"itunes": ITUNES_NS}
    root = ET.fromstring(rss_bytes)
    episodes = []
    for item in root.findall(".//item"):
        guid_el = item.find("guid")
        guid = (guid_el.text or "").strip() if guid_el is not None else ""
        title_el = item.find("title")
        title = (title_el.text or "Untitled").strip() if title_el is not None else "Untitled"
        link_el = item.find("link")
        link = (link_el.text or "").strip() if link_el is not None else ""
        pub_el = item.find("pubDate")
        pub_date = (pub_el.text or "").strip() if pub_el is not None else ""
        desc_el = item.find("description")
        description = desc_el.text if desc_el is not None else ""
        season_el = item.find("itunes:season", ns)
        season = season_el.text if season_el is not None else ""
        dur_el = item.find("itunes:duration", ns)
        duration = dur_el.text if dur_el is not None else ""
        img_el = item.find("itunes:image", ns)
        thumbnail = img_el.get("href", "") if img_el is not None else ""
        if not guid:
            continue
        episodes.append({
            "guid": guid,
            "title": title,
            "link": link,
            "pub_date": pub_date,
            "description": description or "",
            "season": season,
            "duration": duration,
            "thumbnail": thumbnail,
        })
    return episodes


def episode_slug(guid):
    """Same md5-of-guid slug used throughout the pipeline (episode-stats
    filenames, transcript filenames) so this generator's URLs stay stable
    across RSS title edits and line up with existing data files."""
    return hashlib.md5(guid.encode()).hexdigest()[:12]


def strip_html(desc):
    """Mirror of the client-side stripHtml(): insert a space at block
    boundaries before stripping tags, so adjacent <p>/<br> text doesn't
    glue together with no separator."""
    if not desc:
        return ""
    with_gaps = re.sub(r"<\s*br\s*/?\s*>", " ", desc, flags=re.IGNORECASE)
    with_gaps = re.sub(r"</\s*(p|div|li)\s*>", " ", with_gaps, flags=re.IGNORECASE)
    text = re.sub(r"<[^>]+>", " ", with_gaps)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def format_description_html(desc):
    """Mirror of the client-side formatDescriptionHtml(): if the RSS
    description has no block-level HTML tags, treat it as plain text and
    convert blank-line-separated paragraphs into real <p>/<br> markup so
    browsers don't collapse the literal newlines."""
    if not desc:
        return ""
    if re.search(r"<\s*(p|br|div|li)\b", desc, re.IGNORECASE):
        return desc
    paras = re.split(r"\n\s*\n", desc)
    return "".join(
        "<p>" + p.strip().replace("\n", "<br>") + "</p>" for p in paras if p.strip()
    )


# Canonical player first-names (as shown on players.html) mapped to the
# alternate forms that show up in RSS episode descriptions, e.g.
# "Narrated by Vicki" / "Narrated by Victoria Simpson" should both
# resolve to the same player. Longest aliases are tried first so e.g.
# "Robert Simpson" doesn't get partially matched as something else.
NARRATOR_ALIASES = {
    "Rob": ["Rob Simpson", "Robert Simpson", "Rob"],
    "Vicki": ["Vicki Simpson", "Victoria Simpson", "Vicki"],
    "Sean": ["Sean McDermott", "Sean"],
    "David": ["David Lovesy", "David"],
    "Steve": ["Steve Clark", "Steve"],
    "Jodie": ["Jodie Commerical", "Jodie Commercial", "Jodie"],
    "Finley": ["Finley Simpson", "Finley"],
    "Avalon": ["Avalon Simpson", "Avalon"],
    "Gaia": ["Gaia"],
}

# Longest-alias-first flat lookup: alias text -> canonical player name.
_NARRATOR_ALIAS_LOOKUP = sorted(
    ((alias, canon) for canon, aliases in NARRATOR_ALIASES.items() for alias in aliases),
    key=lambda pair: len(pair[0]),
    reverse=True,
)


def extract_narrator(desc_plain):
    """Look for an explicit 'Narrated by <Name>' credit in a plain-text
    (HTML-stripped) episode description and resolve it to a canonical
    player name from NARRATOR_ALIASES. Returns None if there's no such
    credit or the name doesn't resolve to a known player — deliberately
    conservative, since this feeds a public-facing 'episodes narrated by
    X' carousel theme and a wrong credit is worse than a missing one."""
    if not desc_plain:
        return None
    m = re.search(
        r"Narrat(?:ed|or)s?\s*(?:by)?[:\s]+([A-Za-z][A-Za-z .'-]*)",
        desc_plain,
        re.IGNORECASE,
    )
    if not m:
        return None
    raw = m.group(1).strip()
    # Trim off a trailing "Players:"/"Featuring:" etc. that sometimes
    # immediately follows the narrator's name with no punctuation
    # between them in the source description.
    raw = re.split(r"\s+(?:Players|Featuring|Cast)\s*:", raw, flags=re.IGNORECASE)[0].strip()
    for alias, canon in _NARRATOR_ALIAS_LOOKUP:
        if re.match(r"^" + re.escape(alias) + r"\b", raw, re.IGNORECASE):
            return canon
    return None


def load_json(path, default):
    if not path.exists():
        return default
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def esc(s):
    return html.escape(s or "", quote=True)


PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en-GB">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title_esc} \u2014 Puddleford</title>
  <meta name="description" content="{desc_esc}" />
  <meta name="robots" content="index, follow" />
  <link rel="canonical" href="{canonical_url}" />
  <link rel="sitemap" type="application/xml" href="/sitemap.xml" />
  <meta property="og:title" content="{title_esc} \u2014 Puddleford" />
  <meta property="og:description" content="{desc_esc}" />
  <meta property="og:image" content="{image_url}" />
  <meta property="og:url" content="{canonical_url}" />
  <meta property="og:type" content="article" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:site" content="@mktoc" />
  <meta name="twitter:title" content="{title_esc} \u2014 Puddleford" />
  <meta name="twitter:description" content="{desc_esc}" />
  <meta name="twitter:image" content="{image_url}" />
  <meta name="author" content="Milton Keynes Theatre of Comedy" />
  <link rel="icon" href="/favicon.ico" sizes="any" />
  <link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicon-16.png" />
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicon-32.png" />
  <link rel="icon" type="image/png" sizes="192x192" href="/assets/img/favicon-192.png" />
  <link rel="apple-touch-icon" sizes="180x180" href="/assets/img/apple-touch-icon.png" />
  <link rel="stylesheet" href="/assets/css/style.css" />
  <script type="application/ld+json">
  {jsonld}
  </script>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-T0E95LTKN0"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){{dataLayer.push(arguments);}}
  gtag("js", new Date());
  gtag("config", "G-T0E95LTKN0");
</script>
</head>
<body>

<nav class="site-nav">
  <div class="nav-inner">
    <a href="/index.html" class="nav-logo">Puddleford</a>
    <button id="theme-btn" class="theme-nav-dot" aria-label="Change colour theme" title="Change colour theme"><span id="theme-dot"></span></button>
    <button class="nav-hamburger" aria-label="Menu" onclick="this.nextElementSibling.classList.toggle('open')">
      <span></span><span></span><span></span>
    </button>
    <ul class="nav-links">
      <li><a href="/episodes.html">Episodes</a></li>
      <li><a href="/wiki.html">Wiki</a></li>
      <li><a href="/timeline.html">Timeline</a></li>
      <li><a href="/players.html">Players</a></li>
      <li><a href="/events.html">Events</a></li>
      <li><a href="https://open.spotify.com/show/1MhWw8jOD7L36ayZKyHTmd" target="_blank" class="nav-listen">Listen</a></li>
    </ul>
  </div>
</nav>

<main id="episode-main">

  <!-- Hero (baked in at build time \u2014 always correct even without JS) -->
  <section class="ep-hero">
    <div class="ep-hero__inner container">
      <div class="ep-hero__artwork">
        <img id="ep-artwork" class="ep-hero__img" src="{image_url}" alt="{title_esc}" />
      </div>
      <div class="ep-hero__info">
        {badge_html}
        <h1 id="ep-title" class="ep-hero__title">{title_esc}</h1>
        <p id="ep-meta" class="ep-hero__meta">{meta_esc}</p>
        <div id="ep-desc" class="ep-hero__desc">{desc_html}</div>
        <div id="ep-listen" class="ep-hero__listen listen-buttons">{listen_html}</div>
      </div>
    </div>
  </section>

  <!-- Stats bar -->
  <section id="ep-stats-section" class="ep-stats-bar container" style="display:none;">
  </section>

  <!-- Speaking chart -->
  <section id="ep-speaking-section" class="section" style="display:none;">
    <div class="container">
      <h2 class="ep-speaking__title">Who spoke most</h2>
      <div id="ep-speaking-chart" class="ep-speaking"></div>
    </div>
  </section>

  <!-- Characters -->
  <section id="ep-characters-section" class="section" style="display:none;">
    <div class="container">
      <h2 class="ep-section-heading">Principal characters in this episode</h2>
      <div id="ep-characters" class="ep-cards-grid"></div>
    </div>
  </section>

  <!-- Locations -->
  <section id="ep-locations-section" class="section" style="display:none;">
    <div class="container">
      <h2 class="ep-section-heading">Locations in this episode</h2>
      <div id="ep-locations" class="ep-cards-grid"></div>
    </div>
  </section>

  <!-- Transcript -->
  <section id="ep-transcript-section" class="section" style="display:none;">
    <div class="container">
      <button id="ep-transcript-toggle" class="btn btn--outline ep-transcript__toggle">Read transcript</button>
      <div id="ep-transcript-wrap" class="ep-transcript">
        <pre id="ep-transcript-text" class="ep-transcript__text"></pre>
      </div>
    </div>
  </section>

  <!-- Episode navigation -->
  <nav id="ep-nav" class="ep-nav container">
    <a id="ep-prev" class="ep-nav__link ep-nav__link--prev" href="{prev_href}" style="visibility:{prev_vis};">&larr; {prev_title_esc}</a>
    <a href="/episodes.html" class="ep-nav__link ep-nav__link--all">All episodes</a>
    <a id="ep-next" class="ep-nav__link ep-nav__link--next" href="{next_href}" style="visibility:{next_vis};">{next_title_esc} &rarr;</a>
  </nav>

</main>

<footer class="site-footer">
  <div class="footer-inner">
    <div class="footer-brand">
      <a href="/index.html" class="footer-logo">Puddleford</a>
      <p>A Town with a Tale</p>
    </div>
    <div class="footer-links">
      <ul>
        <li><a href="/episodes.html">Episodes</a></li>
        <li><a href="/wiki.html">Wiki</a></li>
        <li><a href="/timeline.html">Timeline</a></li>
        <li><a href="/players.html">Players</a></li>
        <li><a href="/events.html">Events</a></li>
        <li><a href="https://www.mktoc.co.uk/puddleford/" target="_blank">MKTOC</a></li>
      </ul>
    </div>
    <div class="footer-platforms">
      <p>Listen on</p>
      <div data-badges></div>
    </div>
  </div>
  <div class="footer-copy">
    2026 MKTOC, Milton Keynes Theatre of Comedy. All episodes entirely improvised.
  </div>
</footer>

<script src="/assets/js/badges.js"></script>
<script src="/assets/js/episode-enhance.js" data-guid="{guid_esc}" data-title="{title_attr_esc}"></script>
<script src="/assets/js/theme.js"></script>
</body>
</html>
"""


def build_jsonld(ep, canonical_url, image_url, desc_plain):
    schema = {
        "@context": "https://schema.org",
        "@type": "PodcastEpisode",
        "name": ep["title"],
        "url": canonical_url,
        "description": desc_plain[:300],
        "datePublished": ep["pub_date"],
        "partOfSeries": {
            "@type": "PodcastSeries",
            "@id": f"{SITE_URL}/#podcast",
        },
        "image": image_url,
        "inLanguage": "en-GB",
    }
    return json.dumps(schema, indent=2, ensure_ascii=False)


def format_date(pub_date):
    # pub_date is RFC-2822, e.g. "Fri, 10 Jul 2026 04:05:00 GMT"
    m = re.match(r"^\w+, (\d{1,2}) (\w+) (\d{4})", pub_date or "")
    if not m:
        return pub_date or ""
    day, mon, year = m.groups()
    months = {
        "Jan": "January", "Feb": "February", "Mar": "March", "Apr": "April",
        "May": "May", "Jun": "June", "Jul": "July", "Aug": "August",
        "Sep": "September", "Oct": "October", "Nov": "November", "Dec": "December",
    }
    return f"{int(day)} {months.get(mon, mon)} {year}"


def build_page(ep, prev_ep, next_ep):
    slug = episode_slug(ep["guid"])
    canonical_url = f"{SITE_URL}/episodes/{slug}/"
    image_url = ep["thumbnail"] or DEFAULT_IMAGE
    desc_plain = strip_html(ep["description"])
    desc_html = format_description_html(ep["description"])
    meta_bits = [format_date(ep["pub_date"])]
    if ep["duration"]:
        meta_bits.append(ep["duration"])
    meta_text = " \u00b7 ".join(b for b in meta_bits if b)

    badge_html = ""
    if ep["season"]:
        badge_html = f'<span id="ep-badge" class="card__badge">Season {esc(ep["season"])}</span>'

    listen_bits = []
    if ep["link"]:
        listen_bits.append(
            f'<a href="{esc(ep["link"])}" target="_blank" rel="noopener" '
            f'class="listen-btn listen-btn--primary">\u25b6 Play on Spotify</a>'
        )
    listen_bits.append(
        '<a href="https://podcasts.apple.com/podcast/puddleford/id1799546935" '
        'target="_blank" rel="noopener" class="listen-btn">Apple Podcasts</a>'
    )
    listen_bits.append(
        '<a href="https://pca.st/podcast/54648910-c521-013d-5494-0affc0b4f80b" '
        'target="_blank" rel="noopener" class="listen-btn">Pocket Casts</a>'
    )
    listen_html = "".join(listen_bits)

    def nav_link(other_ep, arrow_prefix):
        if not other_ep:
            return "#", "hidden", ""
        other_slug = episode_slug(other_ep["guid"])
        return f"/episodes/{other_slug}/", "visible", esc(other_ep["title"])

    prev_href, prev_vis, prev_title_esc = nav_link(prev_ep, "prev")
    next_href, next_vis, next_title_esc = nav_link(next_ep, "next")

    jsonld = build_jsonld(ep, canonical_url, image_url, desc_plain)

    desc_meta = desc_plain[:200] or "An episode of Puddleford: A Town with a Tale. Entirely improvised audio drama."

    return PAGE_TEMPLATE.format(
        title_esc=esc(ep["title"]),
        desc_esc=esc(desc_meta),
        canonical_url=canonical_url,
        image_url=esc(image_url),
        jsonld=jsonld,
        badge_html=badge_html,
        meta_esc=esc(meta_text),
        desc_html=desc_html,
        listen_html=listen_html,
        prev_href=prev_href,
        prev_vis=prev_vis,
        prev_title_esc=prev_title_esc,
        next_href=next_href,
        next_vis=next_vis,
        next_title_esc=next_title_esc,
        guid_esc=esc(ep["guid"]),
        title_attr_esc=esc(ep["title"]),
    )


def main():
    print("Puddleford static episode page generator")
    print("=" * 40)

    print("Fetching RSS...")
    episodes = parse_episodes(fetch_rss())
    print(f"Found {len(episodes)} episodes.")

    # Chronological order (oldest first) for prev/next nav, same as episode.html.
    # IMPORTANT: pub_date is an RFC-2822 string (e.g. "Fri, 10 Jul 2026...");
    # sorting it as a raw string gives wrong results (e.g. "10 Jul" sorts
    # before "13 Mar" alphabetically). Parse to a real datetime first.
    def pub_date_key(ep):
        try:
            return email.utils.parsedate_to_datetime(ep["pub_date"])
        except (TypeError, ValueError):
            return email.utils.parsedate_to_datetime("Thu, 01 Jan 1970 00:00:00 GMT")
    sorted_eps = sorted(episodes, key=pub_date_key)

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    written = []
    for i, ep in enumerate(sorted_eps):
        prev_ep = sorted_eps[i - 1] if i > 0 else None
        next_ep = sorted_eps[i + 1] if i < len(sorted_eps) - 1 else None
        slug = episode_slug(ep["guid"])
        page_dir = OUT_DIR / slug
        page_dir.mkdir(parents=True, exist_ok=True)
        page_html = build_page(ep, prev_ep, next_ep)
        out_path = page_dir / "index.html"
        out_path.write_text(page_html, encoding="utf-8")
        written.append((ep["guid"], slug, ep["title"]))

    # Write a guid -> slug map so episode.html?id=X can redirect to the
    # matching static page, and so other pages (episodes.html cards,
    # homepage) can link straight to the static URL instead of the old
    # query-string form.
    slug_map = {guid: slug for guid, slug, _ in written}
    with open("data/episode-slugs.json", "w", encoding="utf-8") as f:
        json.dump(slug_map, f, indent=2, ensure_ascii=False)

    print(f"\nWrote {len(written)} static episode pages to {OUT_DIR}/")
    print(f"Wrote slug map to data/episode-slugs.json")

    write_episode_sitemap(written)
    write_episode_index(sorted_eps)


def _canon_episode_title(title):
    """Same normalization as scripts/update_wiki.py's helper of the same
    name: strip a trailing '(era)' suffix so title variants line up
    (RSS titles are sometimes edited to add/change an era suffix)."""
    return re.sub(r"\s*\([^)]*\)\s*$", "", title).strip().lower()


def era_to_century_label(era):
    """Bucket a wiki.json timeline 'era' string (e.g. '1830s', '1215',
    '50 AD', 'Present Day', 'The Wild West', 'Puddlefordia') into a
    coarser century-ish label for the 'small group episodes from an
    era' carousel theme. Non-numeric eras (fictional/contemporary
    settings) are passed through unchanged as their own bucket."""
    era = (era or "").strip()
    if not era:
        return None
    m = re.match(r"^(\d{1,4})", era)
    if not m:
        return era  # "Present Day", "The Wild West", "Puddlefordia", etc.
    year = int(m.group(1))
    if "AD" in era.upper() and year < 100:
        return "1st century AD"
    century_start = (year // 100) * 100
    return f"The {century_start}s"


def write_episode_index(sorted_eps):
    """Single compact per-episode data file for client-side features that
    need lightweight structured data across *all* episodes without
    re-fetching/re-parsing the full RSS feed, all 28 stats files, or
    wiki.json (e.g. the homepage themed carousel, see
    assets/js/carousel.js). Word-count / speaker stats come from
    data/episode-stats/ (already computed by scripts/update_wiki.py);
    era comes from data/wiki.json's timeline (already computed by the
    same script); everything else from RSS.
    """
    stats_index = load_json(EPISODE_STATS_INDEX, {})
    wiki = load_json(WIKI_JSON, {})
    era_by_canon_title = {
        _canon_episode_title(t.get("episode", "")): t.get("era", "")
        for t in wiki.get("timeline", [])
    }

    records = []
    for ep in sorted_eps:
        slug = episode_slug(ep["guid"])
        total_words = 0
        num_speakers = 0
        top_speaker = ""
        stats_path = stats_index.get(ep["guid"])
        if stats_path:
            stats = load_json(Path(stats_path), {})
            speaking = stats.get("speaking") or []
            if speaking:
                total_words = sum(c.get("words", 0) for c in speaking)
                num_speakers = len(speaking)
                top_speaker = speaking[0].get("name", "")
        try:
            dt = email.utils.parsedate_to_datetime(ep["pub_date"])
        except (TypeError, ValueError):
            dt = None
        era = era_by_canon_title.get(_canon_episode_title(ep["title"]), "")
        narrator = extract_narrator(strip_html(ep["description"]))
        records.append({
            "guid": ep["guid"],
            "slug": slug,
            "title": ep["title"],
            "thumbnail": ep["thumbnail"] or DEFAULT_IMAGE,
            "link": ep["link"],
            "pubDate": ep["pub_date"],
            "month": dt.month if dt else None,
            "day": dt.day if dt else None,
            "season": ep["season"],
            "duration": ep["duration"],
            "totalWords": total_words,
            "numSpeakers": num_speakers,
            "topSpeaker": top_speaker,
            "era": era,
            "eraGroup": era_to_century_label(era),
            "narrator": narrator,
        })
    # Newest first, matching every other episode listing on the site.
    records.reverse()
    with open("data/episode-index.json", "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2, ensure_ascii=False)
    print(f"Wrote data/episode-index.json ({len(records)} episodes)")


def write_episode_sitemap(written):
    """Separate sitemap file for episode pages (referenced via
    <sitemapindex> style include from the main sitemap.xml), so this
    generator doesn't need to hand-merge into the manually maintained
    top-level sitemap.xml on every run."""
    import datetime
    today = datetime.date.today().isoformat()
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for _guid, slug, _title in written:
        lines.append("  <url>")
        lines.append(f"    <loc>{SITE_URL}/episodes/{slug}/</loc>")
        lines.append(f"    <lastmod>{today}</lastmod>")
        lines.append("    <changefreq>monthly</changefreq>")
        lines.append("    <priority>0.6</priority>")
        lines.append("  </url>")
    lines.append("</urlset>")
    Path("sitemap-episodes.xml").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote sitemap-episodes.xml ({len(written)} URLs)")


if __name__ == "__main__":
    main()
