#!/usr/bin/env python3
"""
Puddleford Wiki Updater
========================
Fetches the podcast RSS feed, transcribes any new episodes via OpenAI Whisper,
then uses GPT to extract structured wiki data (timeline, locations, characters).
Results are merged into data/wiki.json and transcripts saved to data/transcripts/.

Requires:
  OPENAI_API_KEY environment variable

Usage:
  python3 scripts/update_wiki.py
"""

import os
import sys
import json
import re
import time
import hashlib
import tempfile
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

# ── Config ───────────────────────────────────────────────────────────────────

RSS_URL        = "https://anchor.fm/s/10ce1465c/podcast/rss"
WIKI_JSON      = Path("data/wiki.json")
TRANSCRIPTS_DIR = Path("data/transcripts")
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

TRANSCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
TRANSCRIPT_INDEX = Path("data/transcripts/index.json")

if not OPENAI_API_KEY:
    print("ERROR: OPENAI_API_KEY not set.", file=sys.stderr)
    sys.exit(1)


# ── Helpers ───────────────────────────────────────────────────────────────────

def load_transcript_index():
    if TRANSCRIPT_INDEX.exists():
        with open(TRANSCRIPT_INDEX, "r") as f:
            return json.load(f)
    return {}

def save_transcript_index(index):
    with open(TRANSCRIPT_INDEX, "w") as f:
        json.dump(index, f, indent=2, ensure_ascii=False)

def load_wiki():
    if WIKI_JSON.exists():
        with open(WIKI_JSON, "r") as f:
            return json.load(f)
    return {
        "_meta": {"generated": "", "note": "Auto-generated by wiki-update action."},
        "timeline": [], "locations": [], "characters": [], "processed_episodes": []
    }

def save_wiki(data):
    import datetime
    data["_meta"]["generated"] = datetime.date.today().isoformat()
    with open(WIKI_JSON, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Saved {WIKI_JSON}")

def fetch_rss():
    req = urllib.request.Request(RSS_URL, headers={"User-Agent": "PuddlefordWikiBot/1.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()

def parse_episodes(rss_bytes):
    """Parse RSS and return list of episode dicts."""
    ns = {
        "itunes": "http://www.itunes.com/dtds/podcast-1.0.dtd",
        "content": "http://purl.org/rss/1.0/modules/content/",
    }
    root = ET.fromstring(rss_bytes)
    episodes = []
    for item in root.findall(".//item"):
        guid_el = item.find("guid")
        guid = guid_el.text if guid_el is not None else ""
        title_el = item.find("title")
        title = title_el.text if title_el is not None else "Untitled"
        pub_el = item.find("pubDate")
        pub_date = pub_el.text if pub_el is not None else ""
        enc_el = item.find("enclosure")
        mp3_url = enc_el.get("url", "") if enc_el is not None else ""
        desc_el = item.find("description")
        description = desc_el.text if desc_el is not None else ""
        season_el = item.find("itunes:season", ns)
        season = season_el.text if season_el is not None else ""
        ep_el = item.find("itunes:episode", ns)
        episode_num = ep_el.text if ep_el is not None else ""
        episodes.append({
            "guid": guid,
            "title": title,
            "pub_date": pub_date,
            "mp3_url": mp3_url,
            "description": description,
            "season": season,
            "episode_num": episode_num,
        })
    return episodes

def episode_slug(ep):
    """Safe filename slug from episode guid."""
    return hashlib.md5(ep["guid"].encode()).hexdigest()[:12]

def download_mp3(url, dest_path):
    """Download MP3 to dest_path. Returns True on success."""
    print(f"  Downloading: {url[:80]}...")
    req = urllib.request.Request(url, headers={"User-Agent": "PuddlefordWikiBot/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            data = r.read()
        with open(dest_path, "wb") as f:
            f.write(data)
        print(f"  Downloaded {len(data)//1024}KB")
        return True
    except Exception as e:
        print(f"  Download failed: {e}", file=sys.stderr)
        return False

def transcribe_mp3(mp3_path):
    """Send MP3 to OpenAI Whisper API. Returns transcript text or None."""
    import urllib.request
    url = "https://api.openai.com/v1/audio/transcriptions"
    boundary = "----PuddlefordBoundary7a3f9c"
    with open(mp3_path, "rb") as f:
        mp3_data = f.read()
    # Build multipart body
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="model"\r\n\r\n'
        f"whisper-1\r\n"
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="response_format"\r\n\r\n'
        f"text\r\n"
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="file"; filename="episode.mp3"\r\n'
        f"Content-Type: audio/mpeg\r\n\r\n"
    ).encode() + mp3_data + f"\r\n--{boundary}--\r\n".encode()

    req = urllib.request.Request(
        url,
        data=body,
        headers={
            "Authorization": f"Bearer {OPENAI_API_KEY}",
            "Content-Type": f"multipart/form-data; boundary={boundary}",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=300) as r:
            return r.read().decode("utf-8")
    except urllib.error.HTTPError as e:
        print(f"  Whisper API error {e.code}: {e.read().decode()}", file=sys.stderr)
        return None
    except Exception as e:
        print(f"  Whisper error: {e}", file=sys.stderr)
        return None

def extract_wiki_data(episode_title, episode_desc, transcript):
    """Call GPT to extract structured wiki data from transcript."""
    import json as _json
    prompt = f"""You are a wiki editor for "Puddleford: A Town with a Tale", an entirely improvised episodic audio drama set in a fictional English town.

Given the transcript of episode "{episode_title}", extract factual information (only what is clearly stated in the transcript) and return a JSON object with these fields:

{{
  "timeline_entry": {{
    "era": "The historical period or setting (e.g. '1830s', 'Present Day', 'The Wild West', or null if unclear)",
    "description": "One or two sentences describing what happens in this episode, factually. No invented details."
  }},
  "locations": [
    {{"name": "Location name", "description": "Brief factual description from this episode"}}
  ],
  "characters": [
    {{"name": "Character name", "description": "Brief factual description from this episode"}}
  ]
}}

Rules:
- Only include information clearly present in the transcript.
- Do not invent or embellish anything.
- Keep descriptions concise (1-2 sentences max).
- If a field has no data, use null or an empty array.
- Return only valid JSON, no other text.

Episode description (from RSS):
{episode_desc[:500]}

Transcript:
{transcript[:8000]}
"""
    payload = json.dumps({
        "model": "gpt-4o-mini",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.2,
        "max_tokens": 1000,
    }).encode()

    req = urllib.request.Request(
        "https://api.openai.com/v1/chat/completions",
        data=payload,
        headers={
            "Authorization": f"Bearer {OPENAI_API_KEY}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            resp = json.loads(r.read())
        content = resp["choices"][0]["message"]["content"].strip()
        # Strip markdown code fences if present
        content = re.sub(r"^```json\s*", "", content)
        content = re.sub(r"^```\s*", "", content)
        content = re.sub(r"```$", "", content).strip()
        return json.loads(content)
    except Exception as e:
        print(f"  GPT extraction error: {e}", file=sys.stderr)
        return None

def merge_wiki(wiki, ep, extracted):
    """Merge extracted data into wiki, deduplicating by name/era."""
    title = ep["title"]
    season = ep.get("season", "")

    # Timeline
    if extracted.get("timeline_entry") and extracted["timeline_entry"].get("era"):
        entry = extracted["timeline_entry"]
        # Check if this era+episode combo already exists
        exists = any(
            t.get("era") == entry["era"] and t.get("episode") == title
            for t in wiki["timeline"]
        )
        if not exists:
            wiki["timeline"].append({
                "era": entry["era"],
                "episode": title,
                "description": entry.get("description", ""),
                "source": "transcript",
                "season": season,
            })
            print(f"  + Timeline: {entry['era']} - {title}")

    # Locations
    for loc in (extracted.get("locations") or []):
        if not loc.get("name"):
            continue
        existing = next((l for l in wiki["locations"] if l["name"].lower() == loc["name"].lower()), None)
        if existing:
            # Append episode reference if not already there
            eps = existing.get("episodes", [])
            if title not in eps:
                eps.append(title)
                existing["episodes"] = eps
        else:
            wiki["locations"].append({
                "name": loc["name"],
                "description": loc.get("description", ""),
                "episodes": [title],
                "source": "transcript",
            })
            print(f"  + Location: {loc['name']}")

    # Characters
    for char in (extracted.get("characters") or []):
        if not char.get("name"):
            continue
        existing = next((c for c in wiki["characters"] if c["name"].lower() == char["name"].lower()), None)
        if existing:
            eps = existing.get("episodes", [])
            if title not in eps:
                eps.append(title)
                existing["episodes"] = eps
        else:
            wiki["characters"].append({
                "name": char["name"],
                "description": char.get("description", ""),
                "episodes": [title],
                "source": "transcript",
            })
            print(f"  + Character: {char['name']}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("Puddleford Wiki Updater")
    print("=" * 40)

    wiki = load_wiki()
    processed = set(wiki.get("processed_episodes", []))
    transcript_index = load_transcript_index()

    print(f"Fetching RSS...")
    rss_bytes = fetch_rss()
    episodes = parse_episodes(rss_bytes)
    print(f"Found {len(episodes)} episodes. {len(processed)} already processed.")

    new_episodes = [ep for ep in episodes if ep["guid"] not in processed]
    print(f"{len(new_episodes)} new episodes to process.")

    if not new_episodes:
        print("Nothing to do.")
        return

    for ep in new_episodes:
        print(f"\nProcessing: {ep['title']}")
        slug = episode_slug(ep)
        transcript_path = TRANSCRIPTS_DIR / f"{slug}.txt"
        mp3_path = Path(tempfile.mktemp(suffix=".mp3"))

        try:
            # Check if transcript already exists (from previous partial run)
            if transcript_path.exists():
                print(f"  Using existing transcript.")
                transcript = transcript_path.read_text(encoding="utf-8")
            else:
                if not ep["mp3_url"]:
                    print(f"  No MP3 URL, skipping.")
                    continue
                if not download_mp3(ep["mp3_url"], mp3_path):
                    continue
                print(f"  Transcribing with Whisper...")
                transcript = transcribe_mp3(mp3_path)
                if not transcript:
                    print(f"  Transcription failed, skipping.")
                    continue
                # Save transcript
                transcript_path.write_text(
                    f"# {ep['title']}\n# {ep['pub_date']}\n\n{transcript}",
                    encoding="utf-8"
                )
                print(f"  Transcript saved: {transcript_path}")

            # Update transcript index so the site can serve it
            transcript_index[ep["guid"]] = {
                "file": str(transcript_path),
                "title": ep["title"],
                "pub_date": ep["pub_date"],
                "season": ep.get("season", ""),
                "episode_num": ep.get("episode_num", ""),
            }
            save_transcript_index(transcript_index)

            # Extract wiki data
            print(f"  Extracting wiki data with GPT...")
            extracted = extract_wiki_data(ep["title"], ep["description"], transcript)
            if extracted:
                merge_wiki(wiki, ep, extracted)

            # Mark as processed
            processed.add(ep["guid"])
            wiki["processed_episodes"] = list(processed)

            # Save after each episode (so partial progress is not lost)
            save_wiki(wiki)

            # Be kind to the API
            time.sleep(2)

        finally:
            if mp3_path.exists():
                mp3_path.unlink()

    print(f"\nDone. Wiki updated with {len(new_episodes)} new episodes.")

if __name__ == "__main__":
    main()
