#!/usr/bin/env python3
"""
Puddleford Wiki Updater
========================
Fetches the podcast RSS feed, transcribes any new episodes via OpenAI Whisper,
then uses GPT to extract structured wiki data (timeline, locations, characters).
Results are merged into data/wiki.json and transcripts saved to data/transcripts/.

Requires:
  OPENAI_API_KEY environment variable

Usage:
  python3 scripts/update_wiki.py
"""

import os
import sys
import json
import re
import time
import hashlib
import tempfile
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

# ── Config ───────────────────────────────────────────────────────────────────

RSS_URL          = "https://anchor.fm/s/10ce1465c/podcast/rss"
WIKI_JSON        = Path("data/wiki.json")
TRANSCRIPTS_DIR  = Path("data/transcripts")
EPISODE_STATS_DIR = Path("data/episode-stats")
OPENAI_API_KEY   = os.environ.get("OPENAI_API_KEY", "")

TRANSCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
EPISODE_STATS_DIR.mkdir(parents=True, exist_ok=True)
TRANSCRIPT_INDEX = Path("data/transcripts/index.json")

if not OPENAI_API_KEY:
    print("ERROR: OPENAI_API_KEY not set.", file=sys.stderr)
    sys.exit(1)


# ── Helpers ───────────────────────────────────────────────────────────────────

def load_transcript_index():
    if TRANSCRIPT_INDEX.exists():
        with open(TRANSCRIPT_INDEX, "r") as f:
            return json.load(f)
    return {}

def save_transcript_index(index):
    with open(TRANSCRIPT_INDEX, "w") as f:
        json.dump(index, f, indent=2, ensure_ascii=False)

def load_wiki():
    if WIKI_JSON.exists():
        with open(WIKI_JSON, "r") as f:
            return json.load(f)
    return {
        "_meta": {"generated": "", "note": "Auto-generated by wiki-update action."},
        "timeline": [], "locations": [], "characters": [], "processed_episodes": []
    }

def save_wiki(data):
    import datetime
    data["_meta"]["generated"] = datetime.date.today().isoformat()
    with open(WIKI_JSON, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Saved {WIKI_JSON}")

def fetch_rss():
    req = urllib.request.Request(RSS_URL, headers={"User-Agent": "PuddlefordWikiBot/1.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()

def parse_episodes(rss_bytes):
    """Parse RSS and return list of episode dicts."""
    ns = {
        "itunes": "http://www.itunes.com/dtds/podcast-1.0.dtd",
        "content": "http://purl.org/rss/1.0/modules/content/",
    }
    root = ET.fromstring(rss_bytes)
    episodes = []
    for item in root.findall(".//item"):
        guid_el = item.find("guid")
        guid = guid_el.text if guid_el is not None else ""
        title_el = item.find("title")
        title = title_el.text if title_el is not None else "Untitled"
        pub_el = item.find("pubDate")
        pub_date = pub_el.text if pub_el is not None else ""
        enc_el = item.find("enclosure")
        mp3_url = enc_el.get("url", "") if enc_el is not None else ""
        desc_el = item.find("description")
        description = desc_el.text if desc_el is not None else ""
        season_el = item.find("itunes:season", ns)
        season = season_el.text if season_el is not None else ""
        ep_el = item.find("itunes:episode", ns)
        episode_num = ep_el.text if ep_el is not None else ""
        episodes.append({
            "guid": guid,
            "title": title,
            "pub_date": pub_date,
            "mp3_url": mp3_url,
            "description": description,
            "season": season,
            "episode_num": episode_num,
        })
    return episodes

def episode_slug(ep):
    """Safe filename slug from episode guid."""
    return hashlib.md5(ep["guid"].encode()).hexdigest()[:12]

def download_mp3(url, dest_path):
    """Download MP3 to dest_path. Returns True on success."""
    print(f"  Downloading: {url[:80]}...")
    req = urllib.request.Request(url, headers={"User-Agent": "PuddlefordWikiBot/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            data = r.read()
        with open(dest_path, "wb") as f:
            f.write(data)
        print(f"  Downloaded {len(data)//1024}KB")
        return True
    except Exception as e:
        print(f"  Download failed: {e}", file=sys.stderr)
        return False

def compress_audio(src_path, dest_path):
    """Compress audio to 64kbps mono MP3 using ffmpeg. Returns True on success."""
    import subprocess
    try:
        result = subprocess.run(
            ["ffmpeg", "-y", "-i", str(src_path),
             "-ac", "1",          # mono
             "-ar", "16000",      # 16kHz (sufficient for speech)
             "-b:a", "64k",       # 64kbps
             str(dest_path)],
            capture_output=True, timeout=120
        )
        if result.returncode != 0:
            print(f"  ffmpeg error: {result.stderr.decode()[:200]}", file=sys.stderr)
            return False
        size_mb = dest_path.stat().st_size / 1024 / 1024
        print(f"  Compressed to {size_mb:.1f}MB")
        return True
    except Exception as e:
        print(f"  Compression failed: {e}", file=sys.stderr)
        return False

def transcribe_mp3(mp3_path):
    """Send MP3 to OpenAI Whisper API. Returns transcript text or None."""
    import urllib.request
    url = "https://api.openai.com/v1/audio/transcriptions"
    boundary = "----PuddlefordBoundary7a3f9c"
    with open(mp3_path, "rb") as f:
        mp3_data = f.read()
    # Build multipart body
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="model"\r\n\r\n'
        f"whisper-1\r\n"
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="response_format"\r\n\r\n'
        f"text\r\n"
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="file"; filename="episode.mp3"\r\n'
        f"Content-Type: audio/mpeg\r\n\r\n"
    ).encode() + mp3_data + f"\r\n--{boundary}--\r\n".encode()

    req = urllib.request.Request(
        url,
        data=body,
        headers={
            "Authorization": f"Bearer {OPENAI_API_KEY}",
            "Content-Type": f"multipart/form-data; boundary={boundary}",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=300) as r:
            return r.read().decode("utf-8")
    except urllib.error.HTTPError as e:
        print(f"  Whisper API error {e.code}: {e.read().decode()}", file=sys.stderr)
        return None
    except Exception as e:
        print(f"  Whisper error: {e}", file=sys.stderr)
        return None

def extract_wiki_data(episode_title, episode_desc, transcript):
    """Call GPT to extract structured wiki data from transcript."""
    import json as _json
    prompt = f"""You are a wiki editor for "Puddleford: A Town with a Tale", an entirely improvised episodic audio drama set in a fictional English town.

Given the transcript of episode "{episode_title}", extract factual information (only what is clearly stated in the transcript) and return a JSON object with these fields:

{{
  "timeline_entry": {{
    "era": "The historical period or setting (e.g. '1830s', 'Present Day', 'The Wild West', or null if unclear)",
    "description": "One or two sentences describing what happens in this episode, factually. No invented details."
  }},
  "locations": [
    {{"name": "Location name", "description": "Brief factual description from this episode"}}
  ],
  "characters": [
    {{"name": "Character name", "description": "Brief factual description from this episode"}}
  ]
}}

Rules:
- Only include information clearly present in the transcript.
- Do not invent or embellish anything.
- Keep descriptions concise (1-2 sentences max).
- If a field has no data, use null or an empty array.
- Return only valid JSON, no other text.

Episode description (from RSS):
{episode_desc[:500]}

Transcript:
{transcript[:8000]}
"""
    payload = json.dumps({
        "model": "gpt-4o-mini",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.2,
        "max_tokens": 1000,
    }).encode()

    req = urllib.request.Request(
        "https://api.openai.com/v1/chat/completions",
        data=payload,
        headers={
            "Authorization": f"Bearer {OPENAI_API_KEY}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            resp = json.loads(r.read())
        content = resp["choices"][0]["message"]["content"].strip()
        # Strip markdown code fences if present
        content = re.sub(r"^```json\s*", "", content)
        content = re.sub(r"^```\s*", "", content)
        content = re.sub(r"```$", "", content).strip()
        return json.loads(content)
    except Exception as e:
        print(f"  GPT extraction error: {e}", file=sys.stderr)
        return None

def extract_speaking_stats(episode_title, transcript):
    """Ask GPT to estimate word count per character from the transcript."""
    prompt = f"""From this transcript of "{episode_title}", identify each named character who speaks and estimate their approximate word count.

Return JSON only:
{{
  "characters": [
    {{"name": "Character Name", "words": 450}},
    ...
  ]
}}

Rules:
- Only include characters who actually speak (have dialogue)
- Names should match exactly as spoken/referred to in the transcript
- Order by word count descending
- Return only valid JSON, nothing else

Transcript:
{transcript[:6000]}
"""
    payload = json.dumps({
        "model": "gpt-4o-mini",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.2,
        "max_tokens": 500,
    }).encode()

    req = urllib.request.Request(
        "https://api.openai.com/v1/chat/completions",
        data=payload,
        headers={
            "Authorization": f"Bearer {OPENAI_API_KEY}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            resp = json.loads(r.read())
        content = resp["choices"][0]["message"]["content"].strip()
        content = re.sub(r"^```json\s*", "", content)
        content = re.sub(r"^```\s*", "", content)
        content = re.sub(r"```$", "", content).strip()
        return json.loads(content)
    except Exception as e:
        print(f"  Speaking stats error: {e}", file=sys.stderr)
        return None


def generate_stats_card(slug, ep, wiki_data):
    """Generate an SVG stats card for the episode."""
    title = ep.get("title", "Untitled")
    pub_date = ep.get("pub_date", "")
    season = ep.get("season", "")

    # Wrap title at ~30 chars per line
    words = title.split()
    lines = []
    current = ""
    for w in words:
        if current and len(current) + 1 + len(w) > 30:
            lines.append(current)
            current = w
        else:
            current = (current + " " + w).strip()
    if current:
        lines.append(current)
    lines = lines[:3]  # max 3 lines

    # Find characters and locations for this episode from wiki data
    ep_title = ep.get("title", "")
    characters = []
    locations = []
    for c in wiki_data.get("characters", []):
        if ep_title in (c.get("episodes") or []):
            characters.append(c["name"])
    for l in wiki_data.get("locations", []):
        if ep_title in (l.get("episodes") or []):
            locations.append(l["name"])
    characters = characters[:6]
    locations = locations[:4]

    # Build title lines SVG
    title_y_start = 220 if len(lines) == 1 else (200 if len(lines) == 2 else 180)
    title_svg = ""
    for i, line in enumerate(lines):
        escaped = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
        y = title_y_start + i * 70
        title_svg += f'    <text x="600" y="{y}" text-anchor="middle" font-family="Georgia, serif" font-size="56" font-weight="700" fill="#f2e8d5">{escaped}</text>\n'

    # Date below title
    date_y = title_y_start + len(lines) * 70 + 10
    date_display = pub_date[:16] if pub_date else ""

    # Season badge
    season_badge = ""
    if season:
        season_badge = f'<text x="1170" y="52" text-anchor="end" font-family="Georgia, serif" font-size="22" font-weight="600" fill="#d4982a" letter-spacing="3">SEASON {season}</text>'

    # Characters list
    char_svg = ""
    if characters:
        char_svg += '    <text x="60" y="430" font-family="Georgia, serif" font-size="16" font-weight="600" fill="#9a8870" letter-spacing="2">CHARACTERS THIS EPISODE</text>\n'
        for i, name in enumerate(characters):
            escaped = name.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            char_svg += f'    <text x="60" y="{458 + i * 26}" font-family="Georgia, serif" font-size="20" fill="#f2e8d5">{escaped}</text>\n'

    # Locations list
    loc_svg = ""
    if locations:
        loc_svg += '    <text x="700" y="430" font-family="Georgia, serif" font-size="16" font-weight="600" fill="#9a8870" letter-spacing="2">LOCATIONS</text>\n'
        for i, name in enumerate(locations):
            escaped = name.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            loc_svg += f'    <text x="700" y="{458 + i * 26}" font-family="Georgia, serif" font-size="20" fill="#f2e8d5">{escaped}</text>\n'

    svg = f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630">
  <rect width="1200" height="630" fill="#1a120a"/>
  <rect x="12" y="12" width="1176" height="606" fill="none" stroke="#6a4a1a" stroke-width="2" rx="4"/>
  <text x="30" y="52" font-family="Georgia, serif" font-size="28" font-weight="600" fill="#d4982a" letter-spacing="4">PUDDLEFORD</text>
  {season_badge}
{title_svg}
  <text x="600" y="{date_y}" text-anchor="middle" font-family="Georgia, serif" font-size="24" fill="#9a8870">{date_display}</text>
{char_svg}
{loc_svg}
  <text x="600" y="612" text-anchor="middle" font-family="Georgia, serif" font-size="16" fill="#d4982a">puddleford.com</text>
</svg>"""

    card_path = EPISODE_STATS_DIR / f"{slug}-card.svg"
    card_path.write_text(svg, encoding="utf-8")
    print(f"  SVG card saved: {card_path}")
    return str(card_path)


def save_episode_stats(slug, ep, speaking_data):
    """Save episode speaking stats JSON."""
    stats = {
        "guid": ep.get("guid", ""),
        "title": ep.get("title", ""),
        "pub_date": ep.get("pub_date", ""),
        "season": ep.get("season", ""),
        "speaking": speaking_data.get("characters", []) if speaking_data else [],
    }
    stats_path = EPISODE_STATS_DIR / f"{slug}.json"
    with open(stats_path, "w") as f:
        json.dump(stats, f, indent=2, ensure_ascii=False)
    print(f"  Stats saved: {stats_path}")
    return str(stats_path)


def process_episode_analytics(ep, slug, transcript, wiki):
    """Run speaking stats extraction, SVG card generation for an episode."""
    print(f"  Extracting speaking stats...")
    speaking = extract_speaking_stats(ep["title"], transcript)

    stats_path = save_episode_stats(slug, ep, speaking)
    card_path = generate_stats_card(slug, ep, wiki)

    # Update episode_stats index in wiki
    if "episode_stats" not in wiki:
        wiki["episode_stats"] = {}
    wiki["episode_stats"][ep["guid"]] = f"data/episode-stats/{slug}.json"

    return speaking, stats_path, card_path


def merge_wiki(wiki, ep, extracted):
    """Merge extracted data into wiki, deduplicating by name/era."""
    title = ep["title"]
    season = ep.get("season", "")

    # Timeline
    if extracted.get("timeline_entry") and extracted["timeline_entry"].get("era"):
        entry = extracted["timeline_entry"]
        # Check if this era+episode combo already exists
        exists = any(
            t.get("era") == entry["era"] and t.get("episode") == title
            for t in wiki["timeline"]
        )
        if not exists:
            wiki["timeline"].append({
                "era": entry["era"],
                "episode": title,
                "description": entry.get("description", ""),
                "source": "transcript",
                "season": season,
            })
            print(f"  + Timeline: {entry['era']} - {title}")

    # Locations
    for loc in (extracted.get("locations") or []):
        if not loc.get("name"):
            continue
        existing = next((l for l in wiki["locations"] if l["name"].lower() == loc["name"].lower()), None)
        if existing:
            # Append episode reference if not already there
            eps = existing.get("episodes", [])
            if title not in eps:
                eps.append(title)
                existing["episodes"] = eps
        else:
            wiki["locations"].append({
                "name": loc["name"],
                "description": loc.get("description", ""),
                "episodes": [title],
                "source": "transcript",
            })
            print(f"  + Location: {loc['name']}")

    # Characters
    for char in (extracted.get("characters") or []):
        if not char.get("name"):
            continue
        existing = next((c for c in wiki["characters"] if c["name"].lower() == char["name"].lower()), None)
        if existing:
            eps = existing.get("episodes", [])
            if title not in eps:
                eps.append(title)
                existing["episodes"] = eps
        else:
            wiki["characters"].append({
                "name": char["name"],
                "description": char.get("description", ""),
                "episodes": [title],
                "source": "transcript",
            })
            print(f"  + Character: {char['name']}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("Puddleford Wiki Updater")
    print("=" * 40)

    wiki = load_wiki()
    processed = set(wiki.get("processed_episodes", []))
    transcript_index = load_transcript_index()

    print(f"Fetching RSS...")
    rss_bytes = fetch_rss()
    episodes = parse_episodes(rss_bytes)
    print(f"Found {len(episodes)} episodes. {len(processed)} already processed.")

    new_episodes = [ep for ep in episodes if ep["guid"] not in processed]
    print(f"{len(new_episodes)} new episodes to process.")

    if not new_episodes:
        print("Nothing to do.")
        return

    for ep in new_episodes:
        print(f"\nProcessing: {ep['title']}")
        slug = episode_slug(ep)
        transcript_path = TRANSCRIPTS_DIR / f"{slug}.txt"
        mp3_path = Path(tempfile.mktemp(suffix=".mp3"))

        try:
            # Check if transcript already exists (from previous partial run)
            if transcript_path.exists():
                print(f"  Using existing transcript.")
                transcript = transcript_path.read_text(encoding="utf-8")
            else:
                if not ep["mp3_url"]:
                    print(f"  No MP3 URL, skipping.")
                    continue
                if not download_mp3(ep["mp3_url"], mp3_path):
                    continue
                # Compress to under 25MB before sending to Whisper (API limit)
                compressed_path = Path(tempfile.mktemp(suffix=".mp3"))
                if not compress_audio(mp3_path, compressed_path):
                    print(f"  Compression failed, skipping.")
                    continue
                mp3_path.unlink()  # free space
                mp3_path = compressed_path
                print(f"  Transcribing with Whisper...")
                transcript = transcribe_mp3(mp3_path)
                if not transcript:
                    print(f"  Transcription failed, skipping.")
                    continue
                # Save transcript
                transcript_path.write_text(
                    f"# {ep['title']}\n# {ep['pub_date']}\n\n{transcript}",
                    encoding="utf-8"
                )
                print(f"  Transcript saved: {transcript_path}")

            # Update transcript index so the site can serve it
            transcript_index[ep["guid"]] = {
                "file": str(transcript_path),
                "title": ep["title"],
                "pub_date": ep["pub_date"],
                "season": ep.get("season", ""),
                "episode_num": ep.get("episode_num", ""),
            }
            save_transcript_index(transcript_index)

            # Extract wiki data
            print(f"  Extracting wiki data with GPT...")
            extracted = extract_wiki_data(ep["title"], ep["description"], transcript)
            if extracted:
                merge_wiki(wiki, ep, extracted)

            # Episode analytics (speaking stats + SVG card)
            stats_path = EPISODE_STATS_DIR / f"{slug}.json"
            if not stats_path.exists():
                process_episode_analytics(ep, slug, transcript, wiki)
                time.sleep(1)

            # Mark as processed
            processed.add(ep["guid"])
            wiki["processed_episodes"] = list(processed)

            # Save after each episode (so partial progress is not lost)
            save_wiki(wiki)

            # Be kind to the API
            time.sleep(2)

        finally:
            if mp3_path.exists():
                mp3_path.unlink()

    # Backfill: generate analytics for already-processed episodes missing stats
    print(f"\nBackfill: checking for episodes missing analytics...")
    backfill_count = 0
    for guid, info in transcript_index.items():
        slug_hash = hashlib.md5(guid.encode()).hexdigest()[:12]
        stats_path = EPISODE_STATS_DIR / f"{slug_hash}.json"
        transcript_path = Path(info["file"])
        if not stats_path.exists() and transcript_path.exists():
            transcript = transcript_path.read_text(encoding="utf-8")
            ep_info = {
                "guid": guid,
                "title": info.get("title", ""),
                "pub_date": info.get("pub_date", ""),
                "season": info.get("season", ""),
            }
            print(f"  Backfilling: {ep_info['title']}")
            process_episode_analytics(ep_info, slug_hash, transcript, wiki)
            save_wiki(wiki)
            backfill_count += 1
            time.sleep(2)
    if backfill_count:
        print(f"  Backfilled {backfill_count} episodes.")
    else:
        print(f"  All episodes already have analytics.")

    # Generate episode-stats index.json mapping GUIDs to stats file paths
    stats_index = wiki.get("episode_stats", {})
    stats_index_path = EPISODE_STATS_DIR / "index.json"
    with open(stats_index_path, "w") as f:
        json.dump(stats_index, f, indent=2, ensure_ascii=False)
    print(f"  Wrote {len(stats_index)} entries to {stats_index_path}")

    print(f"\nDone. Wiki updated with {len(new_episodes)} new episodes.")

if __name__ == "__main__":
    main()
